CREATE DATABASE Shopsmart;
USE Shopsmart;
CREATE TABLE Customers(
	CUSTOMER_ID int auto_increment primary key,
	FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
	EMAIL_ID VARCHAR(50) UNIQUE NOT NULL,
    PHONE VARCHAR(15),
    ADDRESS VARCHAR(50),
	CITY VARCHAR(25),
    JOIN_DATE Date
);
DROP TABLE Categories;
create table Categories(
	CATEGORY_ID int auto_increment primary key,
	CATEGORY_NAME VARCHAR(50) NOT NULL UNIQUE
);
create table Products(
	PRODUCT_ID INT AUTO_INCREMENT PRIMARY KEY,
	PRODUCT_NAME VARCHAR(50) NOT NULL,
	CATEGORY_ID INT NOT NULL,
	SUPPLIER VARCHAR(50),
	COST_PRICE DECIMAL(10,2) NOT NULL,
	SELLING_PRICE DECIMAL(10,2) NOT NULL,
	STOCK_QUANTITY INT NOT NULL,
	BRAND VARCHAR(50),
	DATE_OF_ARRIVAL Date
);